services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6380:6379"

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: farstar
      POSTGRES_USER: farstar_user
      POSTGRES_PASSWORD: farstar_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  celery:
    build:
      context: .
      dockerfile: docker/celery/Dockerfile
    container_name: celery
    command: celery -A farstar worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
      - web

volumes:
  postgres_data:
